apiVersion: v1
kind: Service
metadata:
  name: aks-workflow-java
  namespace: namespace-workflow-1741097654141
  labels:
    app.kubernetes.io/name: aks-workflow-java
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aks-workflow-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080